FROM  mcr.microsoft.com/dotnet/sdk:10.0-alpine3.22
#FROM ghcr.io/cyber-dojo-languages/ubuntu-build-essential-24-04:8ab6c08
LABEL maintainer=jon@jaggersoft.com

#ENV DEBIAN_FRONTEND noninteractive
#RUN apt-get install --yes fsharp
